// UnifiedTable - Generated by MiniMax M2.7, adapted for supply-demand-dashboard
// Stitch design: US.MARKET Terminal unified view table

export default function UnifiedTable({ C: theme, data, viewMode, collapsed, setCollapsed, sortStates, handleSort, getSortIndicator, filterRows, getSortedRows, selected, handleSelectRow, toggleFavorite, isInAnyList, isFavorite, setContextMenu, rowRefs, ranges, SECTOR_COLORS, VARSChart, ValueBar, ABCBadge, ScoreCell, SignalBadge }) {

  const s = {
    container: { backgroundColor: theme.surfaceAlt, borderRadius: 8, border: `1px solid ${theme.outlineVar}`, overflow: "hidden", flex: 1 },
    th: { fontFamily: "'Inter', sans-serif", padding: "10px 10px", textAlign: "left", fontSize: 9, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.1em", color: theme.textDim, borderBottom: `1px solid ${theme.outline}`, cursor: "pointer", userSelect: "none", whiteSpace: "nowrap", backgroundColor: theme.surfaceHigh },
    td: { fontFamily: "'Inter', sans-serif", padding: "8px 10px", borderBottom: `1px solid ${theme.borderLight}`, verticalAlign: "middle", fontSize: 10 },
    groupHeader: { padding: "8px 16px", backgroundColor: `${theme.surfaceHighest}80`, color: theme.primary, fontSize: 10, fontWeight: 900, textTransform: "uppercase", letterSpacing: "0.15em", borderTop: `1px solid ${theme.borderLight}`, borderBottom: `1px solid ${theme.borderLight}`, cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center" },
    tickerName: { fontWeight: 800, fontSize: 10, color: theme.textBright, lineHeight: 1.3, letterSpacing: "-0.01em" },
    tickerSub: { fontSize: 7, color: theme.textDim, textTransform: "uppercase", letterSpacing: "0.05em", marginTop: 1 },
    heatCell: (value) => {
      const abs = Math.abs(value || 0);
      const intensity = Math.min(abs / 15, 0.8);
      const color = (value || 0) >= 0 ? theme.primary : theme.secondary;
      return { width: 64, height: 18, borderRadius: 2, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 9, fontWeight: 700, backgroundColor: color, opacity: Math.max(intensity, 0.15), color: intensity > 0.4 ? "#fff" : color };
    },
    signalBadge: (signal) => {
      const base = { padding: "2px 8px", borderRadius: 2, fontSize: 9, fontWeight: 900, textTransform: "uppercase", letterSpacing: "0.05em", whiteSpace: "nowrap" };
      if (signal === "강력매수") return { ...base, backgroundColor: theme.primary, color: "#002109", boxShadow: `0 0 12px ${theme.primary}4d` };
      if (signal === "매수") return { ...base, backgroundColor: `${theme.primary}cc`, color: "#002109" };
      if (signal === "매도") return { ...base, backgroundColor: `${theme.secondary}30`, color: theme.secondary, border: `1px solid ${theme.secondary}50` };
      if (signal === "강력매도") return { ...base, backgroundColor: theme.secondary, color: "#410004" };
      return { ...base, backgroundColor: theme.surfaceHighest, color: theme.textDim, border: `1px solid ${theme.outlineVar}` };
    },
  };

  if (!data) return null;

  return (
    <div style={{ flex: 1, overflowY: "auto", overflowX: "hidden" }}>
      {Object.entries(data).map(([group, rows]) => {
        const isCollapsed = collapsed[group];
        const filteredRows = filterRows(rows);
        const sortedRows = getSortedRows(group, filteredRows);
        const range = ranges[group] || {};
        const sectorColor = SECTOR_COLORS[rows[0]?.sector] || "#666";

        return (
          <div key={group}>
            {/* Group Header */}
            <div onClick={() => setCollapsed(p => ({ ...p, [group]: !p[group] }))} style={s.groupHeader}>
              <span>{isCollapsed ? "▶" : "▼"} {group} <span style={{ fontWeight: 400, color: theme.textDim, fontSize: 10 }}>({sortedRows.length})</span></span>
            </div>

            {!isCollapsed && (
              <table style={{ width: "100%", borderCollapse: "collapse", tableLayout: "fixed" }}>
                <thead>
                  <tr>
                    <th style={{ ...s.th, width: 30 }}>★</th>
                    <th style={{ ...s.th, width: 90 }} onClick={() => handleSort(group, "ticker")}>Ticker{getSortIndicator(group, "ticker")}</th>
                    <th style={{ ...s.th, width: 36 }} onClick={() => handleSort(group, "abc")}>Grd{getSortIndicator(group, "abc")}</th>
                    {viewMode !== "flow" && <>
                      <th style={{ ...s.th, width: 80 }} onClick={() => handleSort(group, "daily")}>Daily{getSortIndicator(group, "daily")}</th>
                      <th style={{ ...s.th, width: 72 }} onClick={() => handleSort(group, "5d")}>5D Heat{getSortIndicator(group, "5d")}</th>
                      <th style={{ ...s.th, width: 72 }} onClick={() => handleSort(group, "20d")}>20D Heat{getSortIndicator(group, "20d")}</th>
                      <th style={{ ...s.th, width: 45 }} onClick={() => handleSort(group, "distSma50Atr")}>ATRx{getSortIndicator(group, "distSma50Atr")}</th>
                      <th style={{ ...s.th, width: 60 }}>VARS</th>
                    </>}
                    {viewMode !== "original" && <>
                      <th style={{ ...s.th, width: 62 }} onClick={() => handleSort(group, "score")}>Flow{getSortIndicator(group, "score")}</th>
                      <th style={{ ...s.th, width: 70 }}>Signal</th>
                      <th style={{ ...s.th, width: 50 }}>Stage</th>
                    </>}
                    {viewMode !== "flow" && <th style={{ ...s.th, width: 85 }}>LETF</th>}
                  </tr>
                </thead>
                <tbody>
                  {sortedRows.map((row, i) => {
                    const isActive = selected?.ticker === row.ticker && selected?.group === row.group;
                    return (
                      <tr key={`${row.group}-${row.ticker}`}
                        ref={el => rowRefs.current[`${row.group}-${row.ticker}`] = el}
                        onClick={() => handleSelectRow(row)}
                        onContextMenu={e => { e.preventDefault(); setContextMenu({ x: e.clientX, y: e.clientY, ticker: row.ticker }); }}
                        style={{ cursor: "pointer", transition: "background 0.15s", backgroundColor: isActive ? theme.surfaceHigh : i % 2 === 0 ? "transparent" : `${theme.surfaceLowest}40` }}
                        onMouseEnter={e => { if (!isActive) e.currentTarget.style.backgroundColor = theme.surfaceHigh; }}
                        onMouseLeave={e => { if (!isActive) e.currentTarget.style.backgroundColor = i % 2 === 0 ? "transparent" : `${theme.surfaceLowest}40`; }}
                      >
                        <td style={{ ...s.td, textAlign: "center", padding: "4px" }}>
                          <span className="material-symbols-outlined"
                            onClick={e => { e.stopPropagation(); toggleFavorite(row.ticker); }}
                            style={{ fontSize: 16, color: isInAnyList(row.ticker) ? "#f59e0b" : theme.outline, cursor: "pointer", fontVariationSettings: isInAnyList(row.ticker) ? "'FILL' 1" : "'FILL' 0" }}>
                            star
                          </span>
                        </td>
                        <td style={s.td}>
                          <div style={s.tickerName}>{row.ticker}</div>
                          <div style={s.tickerSub}>{row.sector}</div>
                        </td>
                        <td style={s.td}><ABCBadge grade={row.abc} /></td>
                        {viewMode !== "flow" && <>
                          <td style={{ ...s.td, fontFamily: "monospace", fontWeight: 700, color: (row.daily || 0) >= 0 ? theme.primary : theme.secondary }}>
                            {(row.daily || 0) >= 0 ? "+" : ""}{(row.daily || 0).toFixed(2)}%
                          </td>
                          <td style={s.td}>
                            <div style={s.heatCell(row["5d"])}>
                              {row["5d"] != null ? `${row["5d"] >= 0 ? "+" : ""}${row["5d"].toFixed(1)}%` : "-"}
                            </div>
                          </td>
                          <td style={s.td}>
                            <div style={s.heatCell(row["20d"])}>
                              {row["20d"] != null ? `${row["20d"] >= 0 ? "+" : ""}${row["20d"].toFixed(1)}%` : "-"}
                            </div>
                          </td>
                          <td style={{ ...s.td, fontSize: 11, fontWeight: 600 }}>{row.distSma50Atr?.toFixed(2)}</td>
                          <td style={s.td}><VARSChart data={row.varsChart} /></td>
                        </>}
                        {viewMode !== "original" && <>
                          <td style={s.td}><ScoreCell score={row.score} /></td>
                          <td style={s.td}><span style={s.signalBadge(row.signal)}>{row.signal}</span></td>
                          <td style={{ ...s.td, fontSize: 10, color: row.phase?.includes("매집") ? theme.primary : row.phase?.includes("분산") || row.phase === "투매" ? theme.secondary : theme.textDim, fontWeight: 600 }}>{row.phase}</td>
                        </>}
                        {viewMode !== "flow" && (
                          <td style={{ ...s.td, fontSize: 10, whiteSpace: "nowrap" }}>
                            {row.longETF?.map(e => <span key={e} style={{ color: theme.greenBright, cursor: "pointer", marginRight: 3 }}>{e}</span>)}
                            {row.shortETF?.map(e => <span key={e} style={{ color: theme.redBright, cursor: "pointer", marginRight: 3 }}>{e}</span>)}
                            {!row.longETF?.length && !row.shortETF?.length && <span style={{ color: theme.outline }}>-</span>}
                          </td>
                        )}
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            )}
          </div>
        );
      })}
    </div>
  );
}
